// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtGFwfR45P_psP3yYtibqlijhDJ0J02Oc',
    appId: '1:29922646312:web:3d58b6360aa66789f2d81d',
    messagingSenderId: '29922646312',
    projectId: 'genome-e2802',
    authDomain: 'genome-e2802.firebaseapp.com',
    storageBucket: 'genome-e2802.appspot.com',
    measurementId: 'G-BDSEPTFSD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI1VaXubssQyNm_qWZh6_shBv6eOwljD0',
    appId: '1:29922646312:android:0362fad4cb9a319ef2d81d',
    messagingSenderId: '29922646312',
    projectId: 'genome-e2802',
    storageBucket: 'genome-e2802.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM8oShsE9CvmfXmLNuH6tBl-YX-t_i2xg',
    appId: '1:29922646312:ios:a359739562140f4df2d81d',
    messagingSenderId: '29922646312',
    projectId: 'genome-e2802',
    storageBucket: 'genome-e2802.appspot.com',
    iosClientId: '29922646312-f8a6kt2frb66vgmr6fgk3n8mk54ngfpk.apps.googleusercontent.com',
    iosBundleId: 'com.Friedman.CENT',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM8oShsE9CvmfXmLNuH6tBl-YX-t_i2xg',
    appId: '1:29922646312:ios:a359739562140f4df2d81d',
    messagingSenderId: '29922646312',
    projectId: 'genome-e2802',
    storageBucket: 'genome-e2802.appspot.com',
    iosClientId: '29922646312-f8a6kt2frb66vgmr6fgk3n8mk54ngfpk.apps.googleusercontent.com',
    iosBundleId: 'com.Friedman.CENT',
  );
}
